// Self-host the three webfonts the design uses. Removes a render-blocking
// third-party stylesheet plus per-page requests to fonts.googleapis.com /
// fonts.gstatic.com — better FCP (N5) and no third-party contact at all (D5).
//
// Output is committed, so the site still builds with the network blocked (N4).
// Run: node scripts/fetch-fonts.mjs

import { mkdir, writeFile } from 'node:fs/promises';

const ROOT = new URL('..', import.meta.url);
const FONT_DIR = new URL('public/fonts/', ROOT);
const CSS_OUT = new URL('src/styles/fonts.css', ROOT);

const FAMILIES = [
  { name: 'Space Grotesk', weights: [400, 500, 600, 700] },
  { name: 'IBM Plex Mono', weights: [400, 500, 600] },
  { name: 'IBM Plex Sans', weights: [400, 500, 600] },
];

// A modern UA makes the CSS API return woff2 with unicode-range subsets.
const UA = 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/124.0 Safari/537.36';

await mkdir(FONT_DIR, { recursive: true });

const blocks = [];
let files = 0;

for (const fam of FAMILIES) {
  const q = `${fam.name.replace(/ /g, '+')}:wght@${fam.weights.join(';')}`;
  const url = `https://fonts.googleapis.com/css2?family=${q}&display=swap`;
  const css = await (await fetch(url, { headers: { 'User-Agent': UA } })).text();

  // Keep only latin + latin-ext subsets; that's all the site's copy needs.
  const faces = css.split('/*').filter((c) => /^\s*(latin|latin-ext)\s*\*\//.test(c));
  for (const face of faces) {
    const subset = face.match(/^\s*(latin-ext|latin)\s*\*\//)[1];
    const weight = face.match(/font-weight:\s*(\d+)/)?.[1] ?? '400';
    const src = face.match(/src:\s*url\(([^)]+)\)/)?.[1];
    const range = face.match(/unicode-range:\s*([^;]+);/)?.[1];
    if (!src) continue;

    const slug = `${fam.name.toLowerCase().replace(/ /g, '-')}-${weight}-${subset}.woff2`;
    const bin = await fetch(src, { headers: { 'User-Agent': UA } });
    if (!bin.ok) throw new Error(`${slug}: HTTP ${bin.status}`);
    await writeFile(new URL(slug, FONT_DIR), Buffer.from(await bin.arrayBuffer()));
    files++;

    blocks.push(
      `@font-face {\n` +
        `  font-family: '${fam.name}';\n` +
        `  font-style: normal;\n` +
        `  font-weight: ${weight};\n` +
        `  font-display: swap;\n` +
        `  src: url('/fonts/${slug}') format('woff2');\n` +
        (range ? `  unicode-range: ${range};\n` : '') +
        `}`,
    );
  }
}

await writeFile(
  CSS_OUT,
  `/* GENERATED by scripts/fetch-fonts.mjs — do not edit.\n` +
    `   Self-hosted so no page contacts fonts.googleapis.com / fonts.gstatic.com. */\n\n` +
    blocks.join('\n\n') +
    '\n',
);

console.log(`fonts: ${files} woff2 files, ${blocks.length} @font-face rules -> src/styles/fonts.css`);
